id = "config-list-empty-plaintext"
argv = ["config", "--list", "-o", "plaintext"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "config-list-empty-plaintext.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
