id = "config-set-output"
argv = ["config", "--set", "output", "plaintext"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "config-set-output.stdout"

[expect.files]
"config:ldcli/config.yml" = "output: plaintext\n"
