id = "config-set-no-arguments"
argv = ["config", "--set", "-o", "plaintext"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "config-set-no-arguments.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
