id = "config-yaml-quoting-title-true"
argv = ["config", "--set", "project", "True", "-o", "plaintext"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "config-yaml-quoting-title-true.stdout"

[expect.files]
"config:ldcli/config.yml" = "project: \"True\"\n"
