id = "config-yaml-quoting-integer"
argv = ["config", "--set", "project", "12345", "-o", "plaintext"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "config-yaml-quoting-integer.stdout"

[expect.files]
"config:ldcli/config.yml" = "project: \"12345\"\n"
