id = "setup-detect-node-invalid-corepack-and-bun"
argv = ["setup", "detect"]
declare = ["config:ldcli/config.yml", "work:bun.lockb", "work:package.json"]
rust = true

[seed]
"work:bun.lockb" = ""
"work:package.json" = "{\"packageManager\": \"yarn@latest\", \"dependencies\": {\"react-native\": \"0.73\"}}\n"

[expect]
status = 0
stdout_file = "setup-detect-node-invalid-corepack-and-bun.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
"work:bun.lockb" = ""
"work:package.json" = "{\"dependencies\":{\"react-native\":\"0.73\"},\"packageManager\":\"yarn@latest\"}\n"
