id = "setup-install-pip-less-venv"
argv = ["setup", "install", "--sdk-id", "python-server-sdk", "--package-manager", "pip"]
declare = ["config:ldcli/config.yml", "work:.venv/pyvenv.cfg", "work:requirements.txt"]
rust = true

[seed]
"work:.venv/pyvenv.cfg" = ""
"work:requirements.txt" = ""

[expect]
status = 0
stdout_file = "setup-install-pip-less-venv.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
"work:.venv/pyvenv.cfg" = ""
"work:requirements.txt" = ""
