id = "setup-detect-node-invalid-json"
argv = ["setup", "detect"]
declare = ["config:ldcli/config.yml", "work:package.json"]
rust = true

[seed]
"work:package.json" = "{\n"

[expect]
status = 1
stdout_file = "setup-detect-node-invalid-json.stdout"
stderr_file = "setup-detect-node-invalid-json.stderr"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
"work:package.json" = "{\n"
