version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of go.mod
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/internal/dev_server/ui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
