{
  "packages": {
    ".": {
      "release-type": "go",
      "bump-minor-pre-major": true,
      "versioning": "default",
      "bootstrap-sha": "0102c9eec733b9c8c20f59108b54162e3262de0a",
      "include-component-in-tag" : false,
      "extra-files": [
        "version/version.go"
      ]
    }
  }
}