#!/bin/bash

set -eo pipefail


# REwrite the test lines above so that the script exits with a non-zero exit code, and emits
# a emssage if any of them fail.

if [ -n "$(gofmt -l cmd)"  ]; then
  echo "cmd/* is not formatted; run gofmt -w -s cmd"
  exit 1
fi

if [ -n "$(gofmt -l internal)"  ]; then
  echo "internal/* is not formatted; run gofmt -w -s internal"
  exit 1
fi

if [ -n "$(gofmt -l ./*.go)"  ]; then
  echo "*.go is not formatted; run gofmt -w -s *.go"
  exit 1
fi



go mod tidy
status=$(git status --porcelain go.mod go.sum)
if [ ! -z "$status" ]; then
	echo "go.mod/go.sum is not tidy; run go mod tidy"
	exit 1
fi
exit 0
