package onboarding

// SDKRecipe maps a detected language/framework to the correct LaunchDarkly SDK
// and provides the agent with the information needed to install and initialize it.
type SDKRecipe struct {
	SDKID          string   `json:"sdk_id"`
	DisplayName    string   `json:"display_name"`
	SDKType        string   `json:"sdk_type"`
	DetectFiles    []string `json:"detect_files"`
	DetectPatterns []string `json:"detect_patterns"`
	PackageManager string   `json:"package_manager"`
	InstallCmd     string   `json:"install_cmd"`
	ImportSnippet  string   `json:"import_snippet"`
	InitSnippet    string   `json:"init_snippet"`
}

// AllSDKRecipes returns the complete set of SDK recipes the agent uses
// during the Detect and Plan steps to match a repo to the right SDK.
func AllSDKRecipes() []SDKRecipe {
	return []SDKRecipe{
		{
			SDKID:          "node-server",
			DisplayName:    "Node.js (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"package.json"},
			DetectPatterns: []string{"express", "fastify", "koa", "hapi", "nestjs", "next", "\"type\": \"module\""},
			PackageManager: "npm",
			InstallCmd:     "npm install @launchdarkly/node-server-sdk --save",
			ImportSnippet:  "const LaunchDarkly = require('@launchdarkly/node-server-sdk');",
			InitSnippet:    "const ldClient = LaunchDarkly.init('YOUR_SDK_KEY');\nawait ldClient.waitForInitialization();",
		},
		{
			SDKID:          "python-server-sdk",
			DisplayName:    "Python (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"requirements.txt", "pyproject.toml", "setup.py", "Pipfile"},
			DetectPatterns: []string{"flask", "django", "fastapi", "starlette"},
			PackageManager: "pip",
			InstallCmd:     "pip install launchdarkly-server-sdk",
			ImportSnippet:  "import ldclient\nfrom ldclient.config import Config",
			InitSnippet:    "ldclient.set_config(Config('YOUR_SDK_KEY'))\nclient = ldclient.get()",
		},
		{
			SDKID:          "go-server-sdk",
			DisplayName:    "Go (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"go.mod", "go.sum"},
			DetectPatterns: []string{"net/http", "gin", "echo", "fiber", "chi"},
			PackageManager: "go",
			InstallCmd:     "go get github.com/launchdarkly/go-server-sdk/v7",
			ImportSnippet:  "ld \"github.com/launchdarkly/go-server-sdk/v7\"",
			InitSnippet:    "ldClient, _ := ld.MakeClient(\"YOUR_SDK_KEY\", 5*time.Second)",
		},
		{
			SDKID:          "java-server-sdk",
			DisplayName:    "Java (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"pom.xml", "build.gradle", "build.gradle.kts"},
			DetectPatterns: []string{"spring", "quarkus", "micronaut", "dropwizard"},
			PackageManager: "maven/gradle",
			InstallCmd:     "Add com.launchdarkly:launchdarkly-java-server-sdk to your build file",
			ImportSnippet:  "import com.launchdarkly.sdk.*;\nimport com.launchdarkly.sdk.server.*;",
			InitSnippet:    "LDClient client = new LDClient(\"YOUR_SDK_KEY\");",
		},
		{
			SDKID:          "ruby-server-sdk",
			DisplayName:    "Ruby (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"Gemfile", "*.gemspec"},
			DetectPatterns: []string{"rails", "sinatra", "hanami"},
			PackageManager: "bundler",
			InstallCmd:     "gem install launchdarkly-server-sdk",
			ImportSnippet:  "require 'ldclient-rb'",
			InitSnippet:    "client = LaunchDarkly::LDClient.new('YOUR_SDK_KEY')",
		},
		{
			SDKID:          "dotnet-server-sdk",
			DisplayName:    ".NET (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"*.csproj", "*.sln", "*.fsproj"},
			DetectPatterns: []string{"Microsoft.AspNetCore", "Microsoft.NET"},
			PackageManager: "nuget",
			InstallCmd:     "dotnet add package LaunchDarkly.ServerSdk",
			ImportSnippet:  "using LaunchDarkly.Sdk;\nusing LaunchDarkly.Sdk.Server;",
			InitSnippet:    "var client = new LdClient(\"YOUR_SDK_KEY\");",
		},
		{
			SDKID:          "php-server-sdk",
			DisplayName:    "PHP (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"composer.json"},
			DetectPatterns: []string{"laravel", "symfony", "slim"},
			PackageManager: "composer",
			InstallCmd:     "composer require launchdarkly/server-sdk",
			ImportSnippet:  "use LaunchDarkly\\LDClient;",
			InitSnippet:    "$client = new LDClient('YOUR_SDK_KEY');",
		},
		{
			SDKID:          "rust-server-sdk",
			DisplayName:    "Rust (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"Cargo.toml"},
			DetectPatterns: []string{"actix", "rocket", "axum", "warp"},
			PackageManager: "cargo",
			InstallCmd:     "cargo add launchdarkly-server-sdk",
			ImportSnippet:  "use launchdarkly_server_sdk::{Client, ConfigBuilder};",
			InitSnippet:    "let client = Client::build(ConfigBuilder::new(\"YOUR_SDK_KEY\").build()).expect(\"client\");",
		},
		{
			SDKID:          "erlang-server-sdk",
			DisplayName:    "Erlang (server-side)",
			SDKType:        "server",
			DetectFiles:    []string{"rebar.config", "mix.exs"},
			DetectPatterns: []string{"erlang", "elixir", "phoenix"},
			PackageManager: "rebar/mix",
			InstallCmd:     "Add ldclient to your rebar.config or mix.exs dependencies",
			ImportSnippet:  "-include_lib(\"ldclient/include/ldclient.hrl\").",
			InitSnippet:    "ldclient:start_instance(\"YOUR_SDK_KEY\")",
		},
		{
			SDKID:          "react-client-sdk",
			DisplayName:    "React (client-side)",
			SDKType:        "client",
			DetectFiles:    []string{"package.json"},
			DetectPatterns: []string{"react", "react-dom", "\"react\":"},
			PackageManager: "npm",
			InstallCmd:     "npm install launchdarkly-react-client-sdk --save",
			ImportSnippet:  "import { asyncWithLDProvider } from 'launchdarkly-react-client-sdk';",
			InitSnippet:    "const LDProvider = await asyncWithLDProvider({ clientSideID: 'YOUR_CLIENT_SIDE_ID' });",
		},
		{
			SDKID:          "vue",
			DisplayName:    "Vue (client-side)",
			SDKType:        "client",
			DetectFiles:    []string{"package.json"},
			DetectPatterns: []string{"vue", "\"vue\":"},
			PackageManager: "npm",
			InstallCmd:     "npm install launchdarkly-vue-client-sdk --save",
			ImportSnippet:  "import { LDPlugin } from 'launchdarkly-vue-client-sdk';",
			InitSnippet:    "app.use(LDPlugin, { clientSideID: 'YOUR_CLIENT_SIDE_ID' });",
		},
		{
			SDKID:          "js-client-sdk",
			DisplayName:    "JavaScript (client-side)",
			SDKType:        "client",
			DetectFiles:    []string{"package.json", "index.html"},
			DetectPatterns: []string{"vanilla", "webpack", "vite", "parcel", "rollup"},
			PackageManager: "npm",
			InstallCmd:     "npm install launchdarkly-js-client-sdk --save",
			ImportSnippet:  "import * as LDClient from 'launchdarkly-js-client-sdk';",
			InitSnippet:    "const client = LDClient.initialize('YOUR_CLIENT_SIDE_ID', context);",
		},
		{
			SDKID:          "node-client-sdk",
			DisplayName:    "Node.js (client-side / Electron)",
			SDKType:        "client",
			DetectFiles:    []string{"package.json"},
			DetectPatterns: []string{"electron"},
			PackageManager: "npm",
			InstallCmd:     "npm install launchdarkly-node-client-sdk --save",
			ImportSnippet:  "const LDClient = require('launchdarkly-node-client-sdk');",
			InitSnippet:    "const client = LDClient.initialize('YOUR_CLIENT_SIDE_ID', context);",
		},
		{
			SDKID:          "swift-client-sdk",
			DisplayName:    "Swift / iOS (client-side)",
			SDKType:        "mobile",
			DetectFiles:    []string{"Package.swift", "Podfile", "*.xcodeproj"},
			DetectPatterns: []string{"UIKit", "SwiftUI", "ios"},
			PackageManager: "swift-pm/cocoapods",
			InstallCmd:     "Add LaunchDarkly to your Package.swift or Podfile",
			ImportSnippet:  "import LaunchDarkly",
			InitSnippet:    "var config = LDConfig(mobileKey: \"YOUR_MOBILE_KEY\")\nLDClient.start(config: config, context: context)",
		},
		{
			SDKID:          "android",
			DisplayName:    "Android (client-side)",
			SDKType:        "mobile",
			DetectFiles:    []string{"build.gradle", "build.gradle.kts", "AndroidManifest.xml"},
			DetectPatterns: []string{"android", "com.android", "androidx"},
			PackageManager: "gradle",
			InstallCmd:     "Add com.launchdarkly:launchdarkly-android-client-sdk to your build.gradle",
			ImportSnippet:  "import com.launchdarkly.sdk.android.*;",
			InitSnippet:    "LDConfig config = new LDConfig.Builder().mobileKey(\"YOUR_MOBILE_KEY\").build();\nLDClient.init(application, config, context);",
		},
		{
			SDKID:          "flutter-client-sdk",
			DisplayName:    "Flutter (client-side)",
			SDKType:        "mobile",
			DetectFiles:    []string{"pubspec.yaml"},
			DetectPatterns: []string{"flutter"},
			PackageManager: "pub",
			InstallCmd:     "flutter pub add launchdarkly_flutter_client_sdk",
			ImportSnippet:  "import 'package:launchdarkly_flutter_client_sdk/launchdarkly_flutter_client_sdk.dart';",
			InitSnippet:    "final config = LDConfig(AutoEnvAttributes.enabled, \"YOUR_MOBILE_KEY\");\nawait LDClient.start(config, context);",
		},
		{
			SDKID:          "react-native",
			DisplayName:    "React Native (client-side)",
			SDKType:        "mobile",
			DetectFiles:    []string{"package.json"},
			DetectPatterns: []string{"react-native"},
			PackageManager: "npm",
			InstallCmd:     "npm install @launchdarkly/react-native-client-sdk --save",
			ImportSnippet:  "import { LDProvider } from '@launchdarkly/react-native-client-sdk';",
			InitSnippet:    "<LDProvider mobileKey=\"YOUR_MOBILE_KEY\">{children}</LDProvider>",
		},
	}
}
