name: Publish Artifacts
description: 'Publish artifacts to Github Release'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  dry-run:
    description: 'Is this a dry run. If so no package will be published.'
    required: false
    default: 'true'
  tag:
    description: 'Tag to upload artifacts to.'
    required: true
outputs:
  hashes: 
    description: sha256sum hashes of built artifacts
    value: ${{ steps.hash.outputs.hashes }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Run Goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release ${{ inputs.dry-run == 'true' && '--skip=publish' || '' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - name: Hash build artifacts for provenance 
      id: hash
      shell: bash
      run: | 
        echo "hashes=$(sha256sum dist/* | base64 -w0)" >> "$GITHUB_OUTPUT"
