name: Publish Artifacts
description: 'Publish artifacts to Github Release'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  homebrew-gh-secret:
    description: 'SSH private key used as a GitHub deploy key for publishing to homebrew-tap.'
    required: true
  dry-run:
    description: 'Is this a dry run. If so no package will be published.'
    required: false
    default: 'true'
  snapshot:
    description: 'Create a snapshot release by passing --snapshot to goreleaser. See also `goreleaser release --help'
    default: 'false'
  skip:
    description: 'Set of steps for goreleaser to skip. See also `goreleaser --skip`'
  tag:
    description: 'Tag to upload artifacts to.'
    required: true

outputs:
  hashes:
    description: sha256sum hashes of built artifacts
    value: ${{ steps.hash.outputs.hashes }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/386
    - name: Set up goreleaser
      # Note: that we're unable to use the normal goreleaser actions and have to use this docker image.
      # This is because the dev server piece of the CLI uses SQLite which requires CGO and cross compilation.
      # We're using the goreleaser-cross image to facilitate this. See also: https://github.com/goreleaser/goreleaser-cross
      shell: bash
      run: |
        CONTAINER_ID="$(
          docker run --detach \
            --volume "$PWD:$PWD" \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --entrypoint tail \
            ghcr.io/goreleaser/goreleaser-cross:latest \
              -f /dev/null
        )"
        docker exec --tty "$CONTAINER_ID" dpkg --add-architecture i386
        docker exec --tty "$CONTAINER_ID" apt-get update
        docker exec --tty "$CONTAINER_ID" apt-get install --no-install-recommends -y -q crossbuild-essential-i386
        docker exec --tty "$CONTAINER_ID" git config --global --add safe.directory '*'
        docker exec --tty "$CONTAINER_ID" echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
        echo "CONTAINER_ID=$CONTAINER_ID" >> "$GITHUB_ENV"

    - name: check docker login
      shell: bash
      run: docker exec
        --workdir "$PWD"
        --tty
        "$CONTAINER_ID"
        cat /home/runner/.docker/config.json

    - name: Run Goreleaser
      shell: bash
      run: docker exec
        --env GITHUB_TOKEN
        --env HOMEBREW_DEPLOY_KEY
        --workdir "$PWD"
        --tty
        "$CONTAINER_ID"
        goreleaser release 
            --verbose 
            ${{ inputs.dry-run == 'true' && '--skip=publish' || '' }}
            ${{ inputs.snapshot == 'true' && '--snapshot' || '' }}
            ${{ inputs.skip == '' && '' || format('--skip={0}', inputs.skip) }}
            --config .goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        HOMEBREW_DEPLOY_KEY: ${{ inputs.homebrew-gh-secret }}
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: ldcli
        path: dist/*
    - name: Hash build artifacts for provenance
      id: hash
      shell: bash
      run: |
        echo "hashes=$(sha256sum dist/*.tar.gz | base64 -w0)" >> "$GITHUB_OUTPUT"
