id = "quickstart-after-root-help"
argv = ["-h", "quickstart"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "quickstart-after-root-help.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
