id = "root-version-short"
argv = ["-v"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "root-version-short.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
