id = "root-help-ld-force-tty"
argv = ["--help"]
declare = ["config:ldcli/config.yml"]
rust = true

[env]
LD_FORCE_TTY = "1"

[expect]
status = 0
stdout_file = "root-help-ld-force-tty.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
