id = "setup-detect-help-short"
argv = ["setup", "detect", "-h"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "setup-detect-help-short.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
