id = "setup-help-topic"
argv = ["help", "setup"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "setup-help-topic.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
