// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/launchdarkly/ldcli/internal/dev_server/model (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination mocks/store.go -package mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/launchdarkly/ldcli/internal/dev_server/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeactivateOverride mocks base method.
func (m *MockStore) DeactivateOverride(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateOverride", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateOverride indicates an expected call of DeactivateOverride.
func (mr *MockStoreMockRecorder) DeactivateOverride(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateOverride", reflect.TypeOf((*MockStore)(nil).DeactivateOverride), arg0, arg1, arg2)
}

// DeleteDevProject mocks base method.
func (m *MockStore) DeleteDevProject(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevProject", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDevProject indicates an expected call of DeleteDevProject.
func (mr *MockStoreMockRecorder) DeleteDevProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevProject", reflect.TypeOf((*MockStore)(nil).DeleteDevProject), arg0, arg1)
}

// GetAvailableVariationsForProject mocks base method.
func (m *MockStore) GetAvailableVariationsForProject(arg0 context.Context, arg1 string) (map[string][]model.Variation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableVariationsForProject", arg0, arg1)
	ret0, _ := ret[0].(map[string][]model.Variation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableVariationsForProject indicates an expected call of GetAvailableVariationsForProject.
func (mr *MockStoreMockRecorder) GetAvailableVariationsForProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableVariationsForProject", reflect.TypeOf((*MockStore)(nil).GetAvailableVariationsForProject), arg0, arg1)
}

// GetDevProject mocks base method.
func (m *MockStore) GetDevProject(arg0 context.Context, arg1 string) (*model.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevProject", arg0, arg1)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevProject indicates an expected call of GetDevProject.
func (mr *MockStoreMockRecorder) GetDevProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevProject", reflect.TypeOf((*MockStore)(nil).GetDevProject), arg0, arg1)
}

// GetDevProjectKeys mocks base method.
func (m *MockStore) GetDevProjectKeys(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevProjectKeys", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevProjectKeys indicates an expected call of GetDevProjectKeys.
func (mr *MockStoreMockRecorder) GetDevProjectKeys(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevProjectKeys", reflect.TypeOf((*MockStore)(nil).GetDevProjectKeys), arg0)
}

// GetOverridesForProject mocks base method.
func (m *MockStore) GetOverridesForProject(arg0 context.Context, arg1 string) (model.Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverridesForProject", arg0, arg1)
	ret0, _ := ret[0].(model.Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverridesForProject indicates an expected call of GetOverridesForProject.
func (mr *MockStoreMockRecorder) GetOverridesForProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverridesForProject", reflect.TypeOf((*MockStore)(nil).GetOverridesForProject), arg0, arg1)
}

// InsertProject mocks base method.
func (m *MockStore) InsertProject(arg0 context.Context, arg1 model.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertProject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertProject indicates an expected call of InsertProject.
func (mr *MockStoreMockRecorder) InsertProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProject", reflect.TypeOf((*MockStore)(nil).InsertProject), arg0, arg1)
}

// UpdateProject mocks base method.
func (m *MockStore) UpdateProject(arg0 context.Context, arg1 model.Project) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockStoreMockRecorder) UpdateProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockStore)(nil).UpdateProject), arg0, arg1)
}

// UpsertOverride mocks base method.
func (m *MockStore) UpsertOverride(arg0 context.Context, arg1 model.Override) (model.Override, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOverride", arg0, arg1)
	ret0, _ := ret[0].(model.Override)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertOverride indicates an expected call of UpsertOverride.
func (mr *MockStoreMockRecorder) UpsertOverride(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOverride", reflect.TypeOf((*MockStore)(nil).UpsertOverride), arg0, arg1)
}
