id = "login-expired-token"
argv = ["login", "--base-uri", "{{BASE_URI}}"]
declare = ["config:ldcli/config.yml"]
rust = true
redact = ["hostname"]

[[http]]
method = "POST"
path = "/internal/device-authorization"
status = 200
body = "{\"deviceCode\": \"{{DEVICE_CODE}}\", \"expiresIn\": 900, \"userCode\": \"{{USER_CODE}}\", \"verificationUri\": \"{{VERIFICATION_URI}}\"}"

[[http]]
method = "POST"
path = "/internal/device-authorization/token"
status = 400
body = "{\"code\": \"expired_token\"}"

[expect]
status = 1
stdout_file = "login-expired-token.stdout"
stderr_file = "login-expired-token.stderr"
requests_file = "login-expired-token.requests"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
