id = "whoami-help-short"
argv = ["whoami", "-h"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "whoami-help-short.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
