id = "ldcli__workflows__list"
argv = ["workflows", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__workflows__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
