id = "ldcli__scheduled-changes__create"
argv = ["scheduled-changes", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__scheduled-changes__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
