id = "ldcli__scheduled-changes__list"
argv = ["scheduled-changes", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__scheduled-changes__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
