id = "ldcli__data-export-destinations__list"
argv = ["data-export-destinations", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__data-export-destinations__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
