id = "ldcli__code-refs__get-root-statistic"
argv = ["code-refs", "get-root-statistic", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__code-refs__get-root-statistic.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
