id = "ldcli__setup__detect"
argv = ["setup", "detect", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__setup__detect.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
