id = "ldcli__custom-roles"
argv = ["custom-roles", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__custom-roles.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
