id = "ldcli__data-export-destinations__create"
argv = ["data-export-destinations", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__data-export-destinations__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
