id = "ldcli__integrations-beta__list-configurations"
argv = ["integrations-beta", "list-configurations", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__integrations-beta__list-configurations.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
