id = "ldcli__webhooks__list"
argv = ["webhooks", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__webhooks__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
