id = "ldcli__contexts"
argv = ["contexts", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__contexts.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
