id = "ldcli__teams__list-maintainers"
argv = ["teams", "list-maintainers", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__teams__list-maintainers.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
