id = "ldcli__releases-beta__create-for-flag"
argv = ["releases-beta", "create-for-flag", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__releases-beta__create-for-flag.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
