id = "ldcli__announcements"
argv = ["announcements", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__announcements.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
