id = "ldcli__relay-proxy-configs__update"
argv = ["relay-proxy-configs", "update", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__relay-proxy-configs__update.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
