id = "ldcli__insights-deployments-beta"
argv = ["insights-deployments-beta", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__insights-deployments-beta.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
