id = "ldcli__code-refs__create-repository"
argv = ["code-refs", "create-repository", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__code-refs__create-repository.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
