id = "ldcli__segments__list-expiring-targets"
argv = ["segments", "list-expiring-targets", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__segments__list-expiring-targets.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
