id = "ldcli__environments__delete"
argv = ["environments", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__environments__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
