id = "ldcli__code-refs__replace-branch"
argv = ["code-refs", "replace-branch", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__code-refs__replace-branch.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
