id = "ldcli__persistent-store-integrations-beta__create-big-segment-store-integration"
argv = ["persistent-store-integrations-beta", "create-big-segment-store-integration", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__persistent-store-integrations-beta__create-big-segment-store-integration.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
