id = "ldcli__audit-log__list"
argv = ["audit-log", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__audit-log__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
