id = "ldcli__metric-groups-beta__create"
argv = ["metric-groups-beta", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__metric-groups-beta__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
