id = "ldcli__audit-log__create-entries"
argv = ["audit-log", "create-entries", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__audit-log__create-entries.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
