id = "ldcli__ai-configs__list-agent-graphs"
argv = ["ai-configs", "list-agent-graphs", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__ai-configs__list-agent-graphs.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
