id = "ldcli__access-tokens__get"
argv = ["access-tokens", "get", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__access-tokens__get.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
