id = "ldcli__flags__get"
argv = ["flags", "get", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flags__get.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
