id = "ldcli__ai-configs__get-ai-tool"
argv = ["ai-configs", "get-ai-tool", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__ai-configs__get-ai-tool.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
