id = "ldcli__approval-requests__create-review"
argv = ["approval-requests", "create-review", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__approval-requests__create-review.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
