id = "ldcli__flags__create-migration-safety-issues"
argv = ["flags", "create-migration-safety-issues", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flags__create-migration-safety-issues.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
