id = "ldcli__workflows__delete"
argv = ["workflows", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__workflows__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
