id = "ldcli__setup__install"
argv = ["setup", "install", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__setup__install.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
