id = "ldcli__code-refs__list-extinctions"
argv = ["code-refs", "list-extinctions", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__code-refs__list-extinctions.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
