id = "ldcli__experiments__list-any-env"
argv = ["experiments", "list-any-env", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__experiments__list-any-env.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
