id = "ldcli__workflow-templates"
argv = ["workflow-templates", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__workflow-templates.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
