id = "ldcli__account-usage-beta__get-mau-usage-by-category"
argv = ["account-usage-beta", "get-mau-usage-by-category", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__account-usage-beta__get-mau-usage-by-category.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
