id = "ldcli__approvals-beta__update-request-settings"
argv = ["approvals-beta", "update-request-settings", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__approvals-beta__update-request-settings.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
