id = "ldcli__projects__create"
argv = ["projects", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__projects__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
