id = "ldcli__custom-roles__create"
argv = ["custom-roles", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__custom-roles__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
