id = "ldcli__workflow-templates__delete"
argv = ["workflow-templates", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__workflow-templates__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
