id = "ldcli__teams__get"
argv = ["teams", "get", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__teams__get.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
