id = "ldcli__completion__powershell"
argv = ["completion", "powershell", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__completion__powershell.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
