id = "ldcli__data-export-destinations__get"
argv = ["data-export-destinations", "get", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__data-export-destinations__get.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
