id = "ldcli__applications-beta__delete"
argv = ["applications-beta", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__applications-beta__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
