id = "ldcli__projects__get"
argv = ["projects", "get", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__projects__get.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
