id = "ldcli__metrics__list"
argv = ["metrics", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__metrics__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
