id = "ldcli__flag-triggers__delete"
argv = ["flag-triggers", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flag-triggers__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
