id = "ldcli__code-refs__delete-repository"
argv = ["code-refs", "delete-repository", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__code-refs__delete-repository.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
