id = "ldcli__environments__list"
argv = ["environments", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__environments__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
