id = "ldcli__ai-configs__create-model-config"
argv = ["ai-configs", "create-model-config", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__ai-configs__create-model-config.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
