id = "ldcli__contexts__list"
argv = ["contexts", "list", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__contexts__list.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
