id = "ldcli__setup"
argv = ["setup", "--help"]
declare = ["config:ldcli/config.yml"]
rust = true

[expect]
status = 0
stdout_file = "ldcli__setup.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
