id = "ldcli__teams__create-members"
argv = ["teams", "create-members", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__teams__create-members.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
