id = "ldcli__flags__create"
argv = ["flags", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flags__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
