id = "ldcli__flag-links-beta__update"
argv = ["flag-links-beta", "update", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flag-links-beta__update.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
