id = "ldcli__flags__update"
argv = ["flags", "update", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__flags__update.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
