id = "ldcli__webhooks__create"
argv = ["webhooks", "create", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__webhooks__create.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
