id = "ldcli__segments__delete"
argv = ["segments", "delete", "--help"]
declare = ["config:ldcli/config.yml"]

[expect]
status = 0
stdout_file = "ldcli__segments__delete.stdout"

[expect.files]
"config:ldcli/config.yml" = "{}\n"
