name: Check OpenAPI updates

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # every minute
    # - cron: "0 16 * * *" # every day at 4pm UTC

jobs:
  check-open-api-spec-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check OpenAPI updates
        run: make openapi-spec-check-updates
