name: Check OpenAPI updates

on:
  schedule:
    - cron: "*/1 * * * *" # every minute
    # - cron: "0 16 * * *" # every day at 4pm UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check OpenAPI updates
    uses: actions/checkout@v4
    - name: Check OpenAPI updates
    run: make openapi-spec-check-updates
