# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dev-server UI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: cd internal/dev-server/ui && npm ci

      - name: Run lint
        run: cd internal/dev-server/ui && npm run lint

      - name: Run tests
        run: cd internal/dev-server/ui && npm test

      - name: Run build
        run: cd internal/dev-server/ui && npm run build

      - name: Check for uncommitted changes
        run: |
          cd internal/dev-server/ui
          git diff --exit-code || (echo 'Error: Uncommitted changes detected after build. Run the build locally and commit the changes.' && exit 1)
