# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-versions:
    uses: ./.github/workflows/go-versions.yml

  build:
    needs: go-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix )}}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Enforce formatting / go mod tidy
      run: |
        ./git/hooks/pre-commit

    - name: Build
      run: go build -o ldcli

    - name: Test
      run: go test -v ./...
